2023-10-20 18:14:59,930 - ERROR - Unhandled exception
Traceback (most recent call last):
  File "PTool.py", line 44, in <module>
    sys.exit(app.exec_())
KeyboardInterrupt
2023-10-20 18:18:16,667 - ERROR - Unhandled exception
Traceback (most recent call last):
  File "PTool.py", line 44, in <module>
    sys.exit(app.exec_())
KeyboardInterrupt
